## Tensor Flow
- Git hub Project Link https://github.com/mrdbourke/tensorflow-deep-learning
- Notebooks Link https://www.learntensorflow.io

In [1]:
import tensorflow as tf
import tensorflow_probability as tfp

In [2]:
print(tf.__version__)

2.17.0


### Using tf.constant()

#### Scalar Tensor/Vector

In [5]:
tensor_scalor = tf.constant(18)
tensor_vector = tf.constant([1,2,3,4,5])
print(tensor_scalor)
print(tensor_vector)
print(tensor_scalor.ndim,tensor_scalor.shape)
print(tensor_vector.ndim,tensor_vector.shape)

tf.Tensor(18, shape=(), dtype=int32)
tf.Tensor([1 2 3 4 5], shape=(5,), dtype=int32)
0 ()
1 (5,)


#### Matrix Tensor

In [6]:
tensor_matrix = tf.constant([[1,12],[3,6]])
print(tensor_matrix)
print(tensor_matrix.ndim,tensor_matrix.shape)

tf.Tensor(
[[ 1 12]
 [ 3  6]], shape=(2, 2), dtype=int32)
2 (2, 2)


In [8]:
tensor_matrix2 = tf.constant([[1.34,4.5],[9,10]])
print(tensor_matrix2)
print(tensor_matrix2.ndim,tensor_matrix2.shape)

tf.Tensor(
[[ 1.34  4.5 ]
 [ 9.   10.  ]], shape=(2, 2), dtype=float32)
2 (2, 2)


#### N- dimensional tensor 

In [9]:
tensor_3dim = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(tensor_3dim)
print(tensor_3dim.ndim,tensor_3dim.shape)

tf.Tensor(
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]], shape=(2, 2, 2), dtype=int32)
3 (2, 2, 2)


### Using tf.variable()

In [10]:
tensor_x = tf.Variable([1,11])
tensor_x[1]
tensor_x[1].assign(22)
tensor_x[1]


<tf.Tensor: shape=(), dtype=int32, numpy=22>

#### Random Tensor

In [25]:
random_gen = tf.random.Generator.from_seed(12)
print(type(random_gen))
tn_random1 = random_gen.normal(shape=(4,2))
print(tn_random1)
tn_random2 = tf.random.Generator.from_seed(12).normal(shape=(2,3))
print(tn_random2)

<class 'tensorflow.python.ops.stateful_random_ops.Generator'>
tf.Tensor(
[[-1.0130816   0.28291714]
 [ 1.2132233   0.46988967]
 [ 0.37944323 -0.6664026 ]
 [ 0.6054596   0.19181173]], shape=(4, 2), dtype=float32)
tf.Tensor(
[[-1.0130816   0.28291714  1.2132233 ]
 [ 0.46988967  0.37944323 -0.6664026 ]], shape=(2, 3), dtype=float32)


### Shuffle Tenosr

In [11]:
tf.random.set_seed(12)
tn_unshuff = tf.constant([[10,20],[11,22],[77,88]])
tn_shuff = tf.random.shuffle(tn_unshuff)
print(tn_unshuff)
print(tn_shuff)


tf.Tensor(
[[10 20]
 [11 22]
 [77 88]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[11 22]
 [10 20]
 [77 88]], shape=(3, 2), dtype=int32)


In [12]:
t1 = tf.ones(shape=(1,2))
t2 = tf.ones([1,2])
print(t1)
print(t2)

tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)
tf.Tensor([[1. 1.]], shape=(1, 2), dtype=float32)


In [13]:
t1 = tf.zeros(shape=(1,2))
t2 = tf.zeros([1,2])
print(t1)
print(t2)

tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)
tf.Tensor([[0. 0.]], shape=(1, 2), dtype=float32)


### Numpy array to tensor

In [14]:
import numpy as np
n_array = np.array([[1,2,3],[4,5,6]])
li = [[1,2,3],[4,5,6]] 
print(n_array)
print(li)

tn_numpy1 = tf.constant(n_array)
print(tn_numpy1)
tn_numpy2 = tf.constant(n_array,shape=(3,2))
print(tn_numpy2)

[[1 2 3]
 [4 5 6]]
[[1, 2, 3], [4, 5, 6]]
tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


### Tensor attributes

In [15]:
tn_4_dim = tf.zeros(shape=(2,3,4,5))
print('Shape of tensor      :',tn_4_dim.shape)
print('Number of dimension  :',tn_4_dim.ndim)
print('Datatype of element  :',tn_4_dim.dtype)
print('Size of tensor       :',tf.size(tn_4_dim))
print('Elements at 0 axis   :',tn_4_dim.shape[0])
print('Elements at last axis:',tn_4_dim.shape[-1])
tn_4_dim

Shape of tensor      : (2, 3, 4, 5)
Number of dimension  : 4
Datatype of element  : <dtype: 'float32'>
Size of tensor       : tf.Tensor(120, shape=(), dtype=int32)
Elements at 0 axis   : 2
Elements at last axis: 5


<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

### Tensor access by index

In [16]:
tn_4_dim = tf.constant([[[[1101,1102,1103,1104],[1111,1112,1113,1114],[1121,1122,1123,1124],[1131,1132,1133,1134]],
                         [[1201,1202,1203,1204],[1211,1212,1213,1214],[1221,1222,1223,1224],[1231,1232,1233,1234]],
                         [[1301,1302,1303,1304],[1311,1312,1313,1314],[1321,1322,1323,1324],[1331,1332,1333,1334]]
                       ],
                        [[[2101,2102,2103,2104],[2111,2112,2113,2114],[2121,2122,2123,2124],[2131,2132,2133,2134]],
                         [[2201,2202,2203,2204],[2211,2212,2213,2214],[2221,2222,2223,2224],[2231,2232,2233,2234]],
                         [[2301,2302,2303,2304],[2311,2312,2313,2314],[2321,2322,2323,2324],[2331,2332,2333,2334]]
                       ]
                       ])
tn_4_dim

<tf.Tensor: shape=(2, 3, 4, 4), dtype=int32, numpy=
array([[[[1101, 1102, 1103, 1104],
         [1111, 1112, 1113, 1114],
         [1121, 1122, 1123, 1124],
         [1131, 1132, 1133, 1134]],

        [[1201, 1202, 1203, 1204],
         [1211, 1212, 1213, 1214],
         [1221, 1222, 1223, 1224],
         [1231, 1232, 1233, 1234]],

        [[1301, 1302, 1303, 1304],
         [1311, 1312, 1313, 1314],
         [1321, 1322, 1323, 1324],
         [1331, 1332, 1333, 1334]]],


       [[[2101, 2102, 2103, 2104],
         [2111, 2112, 2113, 2114],
         [2121, 2122, 2123, 2124],
         [2131, 2132, 2133, 2134]],

        [[2201, 2202, 2203, 2204],
         [2211, 2212, 2213, 2214],
         [2221, 2222, 2223, 2224],
         [2231, 2232, 2233, 2234]],

        [[2301, 2302, 2303, 2304],
         [2311, 2312, 2313, 2314],
         [2321, 2322, 2323, 2324],
         [2331, 2332, 2333, 2334]]]])>

In [21]:
print(tn_4_dim[0,0,0,0]) # First element 
print(tn_4_dim[-1,-1,-1,-1]) # Last element
print('---------------------------------------')
print(tn_4_dim[0,0,0,:])
print('---------------------------------------')
print(tn_4_dim[0,0,:,:])
print('---------------------------------------')
print(tn_4_dim[0,:,:,:])
print('=======================================')
print(tn_4_dim[0,1:3,1:3,1:3])

tf.Tensor(1101, shape=(), dtype=int32)
tf.Tensor(2334, shape=(), dtype=int32)
---------------------------------------
tf.Tensor([1101 1102 1103 1104], shape=(4,), dtype=int32)
---------------------------------------
tf.Tensor(
[[1101 1102 1103 1104]
 [1111 1112 1113 1114]
 [1121 1122 1123 1124]
 [1131 1132 1133 1134]], shape=(4, 4), dtype=int32)
---------------------------------------
tf.Tensor(
[[[1101 1102 1103 1104]
  [1111 1112 1113 1114]
  [1121 1122 1123 1124]
  [1131 1132 1133 1134]]

 [[1201 1202 1203 1204]
  [1211 1212 1213 1214]
  [1221 1222 1223 1224]
  [1231 1232 1233 1234]]

 [[1301 1302 1303 1304]
  [1311 1312 1313 1314]
  [1321 1322 1323 1324]
  [1331 1332 1333 1334]]], shape=(3, 4, 4), dtype=int32)
tf.Tensor(
[[[1212 1213]
  [1222 1223]]

 [[1312 1313]
  [1322 1323]]], shape=(2, 2, 2), dtype=int32)


### Tensor adding dimension

In [22]:
tn_2_dim = tf.constant([[10,20,30],[11,22,33]])
print(tn_2_dim)
tn_3_dim_first = tn_2_dim[tf.newaxis,...]
tn_3_dim_last= tn_2_dim[...,tf.newaxis]
print(tn_3_dim_first)
print(tn_3_dim_last)


tf.Tensor(
[[10 20 30]
 [11 22 33]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[[10 20 30]
  [11 22 33]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[[10]
  [20]
  [30]]

 [[11]
  [22]
  [33]]], shape=(2, 3, 1), dtype=int32)


In [23]:
print('======= Other way ================')
tn_3_dim_first = tf.expand_dims(tn_2_dim,axis=0)
print(tn_3_dim_first)
tn_3_dim_last = tf.expand_dims(tn_2_dim,axis=-1)
print(tn_3_dim_last)
tn_3_dim_middle = tf.expand_dims(tn_2_dim,axis=1)
print(tn_3_dim_middle)

======= Other way ================
tf.Tensor(
[[[10 20 30]
  [11 22 33]]], shape=(1, 2, 3), dtype=int32)
tf.Tensor(
[[[10]
  [20]
  [30]]

 [[11]
  [22]
  [33]]], shape=(2, 3, 1), dtype=int32)
tf.Tensor(
[[[10 20 30]]

 [[11 22 33]]], shape=(2, 1, 3), dtype=int32)


### Broadcasting Tensor with basic math operations

In [24]:
tn_2_dim = tf.constant([[10,20,30],[11,22,33]])
print(tf.multiply(tn_2_dim,2))
print(tn_2_dim)      
tn_2_dim = tf.multiply(tn_2_dim,2)
print(tn_2_dim)
tn_2_new = tf.subtract(tn_2_dim,5)
print(tn_2_new)

tf.Tensor(
[[20 40 60]
 [22 44 66]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[10 20 30]
 [11 22 33]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[20 40 60]
 [22 44 66]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[15 35 55]
 [17 39 61]], shape=(2, 3), dtype=int32)


### Tensor Matrix muliplication
- Resource -> https://www.mathsisfun.com/algebra/matrix-multiplying.html

In [26]:
tn_x = tf.constant([[2,3],[4,5]])
print(tn_x)
tn_y = tf.constant([[10,20],[30,40]])
print(tn_y)
print('----Nomral multiplication-----')
print(tn_x * tn_y)
print('---Dot multiplication-----')
print(tn_x @ tn_y)

# For dot multiplication innner shapr should be mach
print('---Dot multiplication shape matching-----')
tn_x = tf.constant([[2,2,2],[3,3,3]])
print(tn_x)
tn_y = tf.constant([[10,20],[10,20],[10,20]])
print(tn_y)
print('2 x 3 ------> 3 x 2')
print(tn_x @ tn_y)



tf.Tensor(
[[2 3]
 [4 5]], shape=(2, 2), dtype=int32)
tf.Tensor(
[[10 20]
 [30 40]], shape=(2, 2), dtype=int32)
----Nomral multiplication-----
tf.Tensor(
[[ 20  60]
 [120 200]], shape=(2, 2), dtype=int32)
---Dot multiplication-----
tf.Tensor(
[[110 160]
 [190 280]], shape=(2, 2), dtype=int32)
---Dot multiplication shape matching-----
tf.Tensor(
[[2 2 2]
 [3 3 3]], shape=(2, 3), dtype=int32)
tf.Tensor(
[[10 20]
 [10 20]
 [10 20]], shape=(3, 2), dtype=int32)
2 x 3 ------> 3 x 2
tf.Tensor(
[[ 60 120]
 [ 90 180]], shape=(2, 2), dtype=int32)


### Chnage Tensor Datatype

In [27]:
tn_x = tf.constant([[2,2],[3,3]])
print(tn_x.dtype)
tn_cast = tf.cast(tn_x,dtype=tf.int16)
print(tn_cast.dtype)

<dtype: 'int32'>
<dtype: 'int16'>


### Tensor Aggergationdtype

In [28]:
tn_ex = tf.constant([[2,-5,4],[7,-9,12]])
tn_abs = tf.abs(tn_ex)
tn_float = tf.cast(tn_ex,dtype=tf.float32)
print(tn_abs)
print('Minimum of tensor - ',tf.reduce_min(tn_abs))
print('Maximum of tensor - ',tf.reduce_max(tn_abs))
print('Average of tensor - ',tf.reduce_mean(tn_abs))
print('Sum of tensor - ',tf.reduce_sum(tn_abs))
print('Variance math of tensor - ',tf.math.reduce_variance(tn_float))

print('Variance of tensor - ',tfp.stats.variance(tn_abs))
print('Std. Dev of tensor - ',tfp.stats.stddev(tn_float))

tf.Tensor(
[[ 2  5  4]
 [ 7  9 12]], shape=(2, 3), dtype=int32)
Minimum of tensor -  tf.Tensor(2, shape=(), dtype=int32)
Maximum of tensor -  tf.Tensor(12, shape=(), dtype=int32)
Average of tensor -  tf.Tensor(6, shape=(), dtype=int32)
Sum of tensor -  tf.Tensor(39, shape=(), dtype=int32)
Variance math of tensor -  tf.Tensor(49.805557, shape=(), dtype=float32)
Variance of tensor -  tf.Tensor([ 6  4 16], shape=(3,), dtype=int32)
Std. Dev of tensor -  tf.Tensor([2.5 2.  4. ], shape=(3,), dtype=float32)


### Postional Max & Min

In [30]:
tf.random.set_seed(10)
tn_50 = tf.random.uniform(shape=[10,5])
print(tf.argmax(tn_50))
tn_50

tf.Tensor([7 8 9 6 7], shape=(5,), dtype=int64)


<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[0.644151  , 0.8082472 , 0.8976548 , 0.6368902 , 0.6270969 ],
       [0.9936013 , 0.02359486, 0.03668392, 0.5860578 , 0.5740315 ],
       [0.09047401, 0.5755553 , 0.25272822, 0.11045039, 0.61225283],
       [0.1290685 , 0.89660144, 0.06479812, 0.8622047 , 0.82242084],
       [0.4016037 , 0.7659943 , 0.4539342 , 0.32376182, 0.4617684 ],
       [0.32858098, 0.8104389 , 0.1609515 , 0.07981062, 0.5934839 ],
       [0.6243702 , 0.9112947 , 0.88744843, 0.9568223 , 0.436625  ],
       [0.9997524 , 0.24064243, 0.8281152 , 0.54077435, 0.8436167 ],
       [0.33806038, 0.9431902 , 0.08632314, 0.68907607, 0.53072953],
       [0.9125186 , 0.06304038, 0.95265174, 0.8152896 , 0.57640743]],
      dtype=float32)>

### Squeezing of Tensor

In [39]:
tf.random.set_seed(10)
tn_5 = tf.random.uniform(shape=[1,1,1,5])
print(tn_5.shape)
print(tf.squeeze(tn_5).shape)

(1, 1, 1, 5)
(5,)


### One Hot Encoding

In [63]:
color_list = [0,1,2,3]
print(tf.one_hot(color_list,depth=4))
print(tf.one_hot(color_list,depth=4,on_value='ON-XXXX',off_value='OFF-OOOO'))

tf.Tensor(
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]], shape=(4, 4), dtype=float32)
tf.Tensor(
[[b'ON-XXXX' b'OFF-OOOO' b'OFF-OOOO' b'OFF-OOOO']
 [b'OFF-OOOO' b'ON-XXXX' b'OFF-OOOO' b'OFF-OOOO']
 [b'OFF-OOOO' b'OFF-OOOO' b'ON-XXXX' b'OFF-OOOO']
 [b'OFF-OOOO' b'OFF-OOOO' b'OFF-OOOO' b'ON-XXXX']], shape=(4, 4), dtype=string)


### Tenosr Math Operations

In [42]:
tn_x = tf.range(2,8)
tn_y = tf.reshape(tn_x,shape=[3,2])
print(tn_y)
tn_sq = tf.square(tn_y)
print(tn_sq)
tn_sqrt = tf.sqrt(tf.cast(tn_sq,dtype=tf.float32))
print(tn_sqrt)

tf.Tensor(
[[2 3]
 [4 5]
 [6 7]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[ 4  9]
 [16 25]
 [36 49]], shape=(3, 2), dtype=int32)
tf.Tensor(
[[2. 3.]
 [4. 5.]
 [6. 7.]], shape=(3, 2), dtype=float32)


### Tensor & NumPy

In [92]:
import numpy as np
tn_arr = tf.reshape(tf.range(1,11),shape=[5,2])
np_arr = np.array(tn_arr)
print(tn_arr.dtype)
print('Tensor to mumPy conversion\n',np_arr)

np_arr2 = np.arange(11,21).reshape(5,2)
tn_arr2 = tf.constant(np_arr2)
print(tn_arr2.dtype)
print('numPy to Tensor conversion\n',tn_arr2)

<dtype: 'int32'>
Tensor to mumPy conversion
 [[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
<dtype: 'int32'>
numPy to Tensor conversion
 tf.Tensor(
[[11 12]
 [13 14]
 [15 16]
 [17 18]
 [19 20]], shape=(5, 2), dtype=int32)


### Finding access to GPU

In [44]:
tf.config.list_physical_devices()

[PhysicalDevice(name='/physical_device:CPU:0', device_type='CPU')]